# Generated by Django 2.0 on 2017-12-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsgonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('biography', models.TextField(default='staff')),
            ],
        ),
    ]
