# Generated by Django 2.0 on 2018-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsgonline', '0003_staffmember_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(default='content')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_shown', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
